# Generated by Django 2.0.3 on 2018-08-24 21:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0064_productvariant_handle_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128)),
                ('background_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='super-collection-backgrounds')),
                ('is_published', models.BooleanField(default=False)),
                ('alternative_name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True, help_text='CMS-able content.')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('collections', models.ManyToManyField(related_name='super_collections', to='product.Collection')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='super_collections.SuperCollection')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('view', 'Can view super collections'), ('edit', 'Can edit super collections')),
            },
        ),
    ]
