# Generated by Django 2.0.3 on 2018-08-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercollection',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='super_collections', to='product.Collection'),
        ),
    ]
