# Generated by Django 2.0.3 on 2018-09-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0002_auto_20180829_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercollection',
            name='custom_slug',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
    ]
