# Generated by Django 2.0.3 on 2018-09-25 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_productvariant_handle_stock'),
        ('super_collections', '0002_auto_20180829_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercollection',
            name='best_seller_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.Product'),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='best_seller_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.Product'),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='best_seller_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.Product'),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='best_seller_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.Product'),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='best_seller_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.Product'),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='best_seller_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.Product'),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_1_to_3_box_button_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_1_to_3_box_header_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_1_to_3_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_4_box_button_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_4_box_header_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_4_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='next_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='next_picture_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='next_picture_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_1_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_1_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_2_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_2_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_3_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_3_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_4_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_4_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_5_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='popular_collection_5_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='previous_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='previous_picture_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='previous_picture_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
