# Generated by Django 2.0.3 on 2018-09-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0003_auto_20180925_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_1_to_3_box_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_4_box_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
