# Generated by Django 2.0.3 on 2018-09-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0004_auto_20180925_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_1_to_3_box_subheader_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picture_4_box_header_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supercollection',
            name='main_picutre_1_to_3_box_header_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
