# Generated by Django 2.0.3 on 2018-09-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0005_auto_20180925_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supercollection',
            old_name='main_picutre_1_to_3_box_header_text',
            new_name='main_picture_1_to_3_box_header_text',
        ),
    ]
