# Generated by Django 2.0.3 on 2018-09-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0006_auto_20180925_2330'),
        ('super_collections', '0003_supercollection_custom_slug'),
    ]

    operations = [
    ]
