# Generated by Django 2.0.3 on 2018-09-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0007_merge_20180928_0026'),
        ('super_collections', '0007_merge_20180928_0022'),
    ]

    operations = [
    ]
