# Generated by Django 2.0.3 on 2018-10-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0009_supercollection_show_in_root_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercollection',
            name='hide_sidebar',
            field=models.BooleanField(default=False),
        ),
    ]
