# Generated by Django 2.0.3 on 2018-11-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0010_supercollection_hide_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercollection',
            name='subheader',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
