# Generated by Django 2.0.10 on 2019-02-28 19:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0011_supercollection_subheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercollection',
            name='collection_ordering',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
    ]
