# Generated by Django 2.0.10 on 2019-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0012_supercollection_collection_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supercollection',
            options={'ordering': ['sort_order'], 'permissions': (('view', 'Can view super collections'), ('edit', 'Can edit super collections'))},
        ),
        migrations.AddField(
            model_name='supercollection',
            name='sort_order',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
