# Generated by Django 2.0.10 on 2019-07-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0013_auto_20190419_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercollection',
            name='show_children_in_side_nav',
            field=models.BooleanField(default=False),
        ),
    ]
