# Generated by Django 2.0.10 on 2019-07-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0014_supercollection_show_children_in_side_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercollection',
            name='appears_in',
            field=models.ManyToManyField(blank=True, related_name='step_children', to='super_collections.SuperCollection'),
        ),
    ]
