# Generated by Django 2.0.10 on 2019-08-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0015_supercollection_appears_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercollection',
            name='show_collections',
            field=models.BooleanField(default=False),
        ),
    ]
