# Generated by Django 2.0.10 on 2019-08-19 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_collections', '0016_supercollection_show_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercollection',
            name='seo_description',
            field=models.CharField(blank=True, max_length=165, null=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='supercollection',
            name='seo_title',
            field=models.CharField(blank=True, max_length=65, null=True, validators=[django.core.validators.MaxLengthValidator(70)]),
        ),
    ]
